[package]
name = "test_b"
type = "lib"
authors = [""]
compiler_version = "0.37.0"

[dependencies]
# c = { path = "../test_c" }
c = { tag = "main", git = "https://github.com/iAmMichaelConnor/test_c.git" }
